server:
  port: 3000
  cors: true
  timezone: 'America/Sao_Paulo'
  bodyLimit: '5mb'

origin:
  - 'http://localhost:80'
  - 'http://localhost'
  - 'http://localhost:8080'  
  - 'http://localhost:9000'

jwt:
  expiresIn: 3600
  secret: 'teste'

llm:
  maxTokens: 1000
